name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Packages
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install nodejs npm
        sudo npm install -g n
        sudo n lts
        sudo npm install -g pug-cli